jets_calibration:
  apply_jec_nominal:
    2016_PreVFP: False
    2016_PostVFP: False
    "2017": False
    "2018": False
    2022_preEE: False
    2022_postEE: False
    2023_preBPix: False
    2023_postBPix: False