scaleout: 300
chunksize: 20000
mem-per-worker: "4GB"
disk-per-worker: "4GB"
cores-per-worker: 1
adaptive: false
queue: "workday"
walltime: "12:00:00"
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
worker-image: "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/pocketcoffea:lxplus-el9-latest"
