spanet:
  file: "/work/mmarcheg/AnalysisConfigs/configs/ttHbb/semileptonic/dctr/params/spanet/spanet.onnx"
dctr:
  file: "/work/mmarcheg/AnalysisConfigs/configs/ttHbb/semileptonic/dctr/params/dctr/model.onnx"
  input_features:
    - njet
    - nbjet
    - ht
    - ht_b
    - ht_light
    - drbb_min
    - mbb_closest
    - bjet_pt_3
  standard_scaler:
    file: "${config_dir:}/standard_scaler/features_8/standard_scaler_tthbb_0p40To0p75_train_1837027.pkl"
  weight_cuts:
    inclusive:
      file: "${config_dir:}/dctr/weight_cuts_tthbb_0p40To0p75.json"
    by_njet:
      file: "${config_dir:}/dctr/weight_cuts_by_njet_tthbb_0p40To0p75.json"
  njet_reweighting:
    file: "${config_dir:}/dctr/reweighting_map_1d.yaml"
    key: tthbb0p40To1p00_ttlf0p30
