plotting_style:
  labels_mc:
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: "$t\\bar{t}$+C (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+B: "$t\\bar{t}$+B (5FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C: "$t\\bar{t}$+C (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: "$t\\bar{t}$+B (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_L: "$t\\bar{t}$+B (4FS) 4j L"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_M: "$t\\bar{t}$+B (4FS) 4j M"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_H: "$t\\bar{t}$+B (4FS) 4j H"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_L: "$t\\bar{t}$+B (4FS) 5j L"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_M: "$t\\bar{t}$+B (4FS) 5j M"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_H: "$t\\bar{t}$+B (4FS) 5j H"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_L: "$t\\bar{t}$+B (4FS) 6j L"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_M: "$t\\bar{t}$+B (4FS) 6j M"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_H: "$t\\bar{t}$+B (4FS) 6j H"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_L: "$t\\bar{t}$+B (4FS) >=7j L"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_M: "$t\\bar{t}$+B (4FS) >=7j M"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_H: "$t\\bar{t}$+B (4FS) >=7j H"
    TTTo2L2Nu : "$t\\bar{t}$ dilepton"
    SingleTop : "Single t"
    ttHTobb: "$t\\bar{t}H$"
    TTV: "$t\\bar{t}$+V"
    VV: "VV"

  samples_groups:
    "V+jets":
      - WJetsToLNu_HT
      - DYJetsToLL

  colors_mc:
    ttHTobb: CMS_red
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: CMS_dark_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: CMS_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: CMS_blue
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_L: "#b84f00"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_M: "#bd5100"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_H: "#c25300"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_L: "#c65500"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_M: "#cb5700"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_H: "#cf5900"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_L: "#d45b00"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_M: "#d95d00"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_H: "#dd5f00"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_L: "#e26100"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_M: "#e76300"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_H: "#eb6400"
    TTTo2L2Nu: CMS_brown
    SingleTop: CMS_gray
    "V+jets": CMS_purple
    TTV: CMS_light_blue
    VV: CMS_beige

  only_samples:
    - DATA_SingleEle
    - DATA_SingleMuon
    - ttHTobb
    - TTToSemiLeptonic__TTToSemiLeptonic_tt+LF
    - TTToSemiLeptonic__TTToSemiLeptonic_tt+C
    - TTTo2L2Nu
    - SingleTop
    - TTV
    - VV
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_L
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_M
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_H
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_L
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_M
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_H
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_L
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_M
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_H
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_L
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_M
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_H

  exclude_samples:
    - ttHTobb_ttToSemiLep
    - TTToSemiLeptonic__TTToSemiLeptonic_tt+B
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_L
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_M
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_4j_DCTR_H
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_L
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_M
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_5j_DCTR_H
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_L
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_M
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_6j_DCTR_H
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_L
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_M
    #- TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B_>=7j_DCTR_H

  rescale_samples:
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: 1.0

  opts_figure:
    datamc:
      figsize: [12,9]

  opts_ylim:
    datamc:
      ylim_log:
        lo: 1.0
        hi: 1e7

  opts_sig:
    histtype: "step"
    stack: false
    flow: "sum"
    edges: true
    linestyle: solid
    linewidth: 1

  blind_hists:
    categories: [semilep, SR, 4jSR, 5jSR, '>=6jSR']
    histograms:
      spanet_tthbb_transformed: [0.75, 1.0]
      spanet_tthbb: [0.75, 1.0]
      spanet_ttlf: [0.0, 0.3]
