quantile_transformer:
  2016_PreVFP:
    n_quantiles: 1000000
    output_distribution: uniform
    file: "${config_dir:}/quantile_transformer/quantiles_regressed.pkl"
  2016_PostVFP:
    n_quantiles: 1000000
    output_distribution: uniform
    file: "${config_dir:}/quantile_transformer/quantiles_regressed.pkl"
  '2017':
    n_quantiles: 1000000
    output_distribution: uniform
    file: "${config_dir:}/quantile_transformer/quantiles_regressed.pkl"
  '2018':
    n_quantiles: 1000000
    output_distribution: uniform
    file: "${config_dir:}/quantile_transformer/quantiles_regressed.pkl"
