btagging:
  working_point:
    2016_PreVFP:
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2016preVFP/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0508
        M: 0.2598
        H: 0.6502
    2016_PostVFP:
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2016postVFP/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0480
        M: 0.2489
        H: 0.6377
    '2017':
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2017/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0532
        M: 0.3040
        H: 0.7476
    '2018':
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2018/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0490
        M: 0.2783
        H: 0.7100
