scaleout: 300
chunksize: 50000
mem-per-worker: "4GB"
disk-per-worker: "4GB"
queue: "standard"
walltime: "6:00:00"
adaptive: false
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
group-samples:
  VJets:
    - "WJetsToLNu_HT"
    - "DYJetsToLL"
  VV_TTV:
    - "VV"
    - "TTV"
