plotting_style:
  labels_mc:
    TTToSemiLeptonic__TTToSemiLeptonic_TT+LF: "$t\\bar{t}$+LF (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_TT+C: "$t\\bar{t}$+C (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_TT+B: "$t\\bar{t}$+B (5FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+LF: "$t\\bar{t}$+LF (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+C: "$t\\bar{t}$+C (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+B: "$t\\bar{t}$+B (4FS)"
    TTTo2L2Nu : "$t\\bar{t}$ dilepton"

  colors_mc:
    ttHTobb: pink
    TTTo2L2Nu: 
      - 0.51
      - 0.79
      - 1.0  # blue
    TTToSemiLeptonic__TTToSemiLeptonic_TT+LF: '#ffcb3d' # light orange
    TTToSemiLeptonic__TTToSemiLeptonic_TT+C: '#ffb53d' # orange
    TTToSemiLeptonic__TTToSemiLeptonic_TT+B: '#ff983d' # dark orange
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+LF: '#39ce31' # dark green
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+C: '#98e838' # lime green
    TTbbSemiLeptonic__TTbbSemiLeptonic_TT+B: '#ccf43a' # light green
    SingleTop:
      - 1.0
      - 0.4
      - 0.4  # red
    WJetsToLNu_HT: '#cc99ff'  # violet

  opts_mc:
    histtype: step
    stack: false
    flow: sum
    edges: false
