import math

axis_settings = {
    'muon_pt': {
        "field": "pt",
        "bins": 50,
        "start": 0,
        'stop': 500,
        "lim": (0, 500),
        'label': "$p_{T}^{\mu}$ [GeV]",
    },
    'muon_eta': {
        "field": "eta",
        "bins": 50,
        "start": -2.5,
        'stop': 2.5,
        "lim": (-2.5, 2.5),
        'label': "$\eta_{\mu}$",
    },
    'muon_phi': {
        "field": "phi",
        "bins": 64,
        "start": -math.pi,
        'stop': math.pi,
        "lim": (-math.pi, math.pi),
        'label': "$\phi_{\mu}$",
    },
    'electron_pt': {
        "field": "pt",
        "bins": 50,
        "start": 0,
        'stop': 500,
        "lim": (0, 500),
        'label': "$p_{T}^{e}$ [GeV]",
    },
    'electron_eta': {
        "field": "eta",
        "bins": 50,
        "start": -2.5,
        'stop': 2.5,
        "lim": (-2.5, 2.5),
        'label': "$\eta_{e}$",
    },
    'electron_phi': {
        "field": "phi",
        "bins": 64,
        "start": -math.pi,
        'stop': math.pi,
        "lim": (-math.pi, math.pi),
        'label': "$\phi_{e}$",
    },
    'jet_pt': {
        "field": "pt",
        "bins": 50,
        "start": 0,
        'stop': 500,
        "lim": (0, 500),
        'label': "$p_{T}^{j}$ [GeV]",
    },
    'jet_eta': {
        "field": "eta",
        "bins": 50,
        "start": -2.5,
        'stop': 2.5,
        "lim": (-2.5, 2.5),
        'label': "$\eta_{j}$",
    },
    'jet_phi': {
        "field": "phi",
        "bins": 64,
        "start": -math.pi,
        'stop': math.pi,
        "lim": (-math.pi, math.pi),
        'label': "$\phi_{j}$",
    },
    'jet_btagDeepFlavB': {
        "field": "btagDeepFlavB",
        "bins": 50,
        "start": 0.0,
        'stop': 1.0,
        "lim": (0, 1),
        'label': "AK4 DeepJet b-tag score",
    },
    'met_pt': {
        "field": "pt",
        "bins": 28,
        "start": 20,
        'stop': 300,
        "lim": (20, 300),
        'label': "MET [GeV]",
    },
    'met_phi': {
        "field": "phi",
        "bins": 64,
        "start": -math.pi,
        'stop': math.pi,
        "lim": (-math.pi, math.pi),
        'label': "MET $\phi$",
    },
}
