plotting_style:
  labels_mc:
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: "$t\\bar{t}$+C (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+B: "$t\\bar{t}$+B (5FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C: "$t\\bar{t}$+C (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: "$t\\bar{t}$+B (4FS)"
    TTTo2L2Nu : "$t\\bar{t}$ dilepton"
    SingleTop : "Single t"
    ttHTobb: "$t\\bar{t}$+H"
    TTV: "$t\\bar{t}$+V"
    VV: "VV"

  samples_groups:
    "V+jets":
      - WJetsToLNu_HT
      - DYJetsToLL

  colors_mc:
    ttHTobb: CMS_red
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: CMS_dark_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: CMS_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: CMS_blue
    TTTo2L2Nu: CMS_brown
    SingleTop: CMS_gray
    "V+jets": CMS_purple
    TTV: CMS_light_blue
    VV: CMS_beige


  exclude_samples:
    - ttHTobb_ttToSemiLep
    - TTToSemiLeptonic__TTToSemiLeptonic_tt+B
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C

  rescale_samples:
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: 1.0

  opts_figure:
    datamc:
      figsize: [12,9]

  opts_ylim:
    datamc:
      ylim_log:
        lo: 1.0
        hi: 1e7

  opts_sig:
    histtype: "step"
    stack: false
    flow: "sum"
    edges: true
    linestyle: solid
    linewidth: 1
