scaleout: 300
chunksize: 400000
mem-per-worker: "6GB"
disk-per-worker: "20GB"
queue: "standard"
walltime: "4:00:00"
tree-reduction: 5
adaptive: false
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
#sched-url: "tcp://192.33.123.29:40714"
group-samples:
  signal:
    - "ttHTobb"
    - "ttHTobb_ttToSemiLep"
  ttbar:
    - "TTToSemiLeptonic"
    - "TTbbSemiLeptonic"
    - "TTTo2L2Nu"
  minor_backgrounds:
    - "SingleTop"
    - "WJetsToLNu_HT"
    - "DYJetsToLL"
    - "VV"
    - "TTV"
  DATA:
    - "DATA_SingleEle"
    - "DATA_SingleMuon"
