dnn_input_variables={
    "era":     ["events","era"],
    "higgs1_reco_pt":["HiggsLeading", "pt"],
    "higgs1_reco_eta": ["HiggsLeading", "eta"],
    "higgs1_reco_phi": ["HiggsLeading", "phi"],
    "higgs1_reco_mass": ["HiggsLeading", "mass"],
    "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
    "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
    "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
    "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
    "HT": ["events", "HT"],
    "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
    "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
    "minDeltaR_Higgjj": ["events", "dR_min"],
    "maxDeltaR_Higgjj": ["events", "dR_max"],
    "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
    "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
    "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
    "hh_vec_mass": ["HH", "mass"],
    "hh_vec_pt": ["HH", "pt"],
    "hh_vec_eta": ["HH", "eta"],
    "hh_vec_DeltaR": ["HH", "dR"],
    "hh_vec_DeltaPhi": ["HH", "dPhi"],
    "hh_vec_DeltaEta": ["HH", "dEta"],
    "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
    "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
    "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
    "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
    "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
    "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
    "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
    "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
    "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
    "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
    "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
    "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
    "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
    "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
    "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
    "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
    "add_jet1pt_pt": ["JetGood:4", "pt"],
    "add_jet1pt_eta": ["JetGood:4", "eta"],
    "add_jet1pt_phi": ["JetGood:4", "phi"],
    "add_jet1pt_mass": ["JetGood:4", "mass"],
    "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
    "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
}
