scaleout: 300
chunksize: 120000
mem-per-worker: "8GB"
disk-per-worker: "4GB"
cores-per-worker: 1
adaptive: false
queue: "standard"
walltime: "12:00:00"
performance-report: false
custom-setup-commands: null
conda-env: false
local-virtualenv: false
spanet_model: "/eos/user/d/dvalsecc/AnalysisConfigs/configs/ttHbb/semileptonic/sig_bkg_classifier/spanet.onnx"
dctr_model: "/eos/user/m/mmarcheg/ttHbb/dctr/training/reweigh_njet_v2/binary_classifier_26features_full_Run2_batch8092_lr5e-4_decay1e-3/lightning_logs/version_1/model_epoch700.onnx"
sched-url: tls://10.100.111.244:31972
tree-reduction: 10
retries: 2