scaleout: 300
chunksize: 4096
mem-per-worker: "8GB"
disk-per-worker: "4GB"
cores-per-worker: 1
adaptive: false
queue: "standard"
walltime: "12:00:00"
performance-report: false
custom-setup-commands: null
conda-env: false
local-virtualenv: false
spanet_model: "/eos/user/m/mmarcheg/ttHbb/models/meanloss_multiclassifier_btag_LMH/spanet_output/version_0/spanet.onnx"
dctr_model: "/eos/user/m/mmarcheg/ttHbb/dctr/training/reweigh_njet_v2/binary_classifier_26features_full_Run2_batch8092_lr5e-4_decay1e-3/lightning_logs/version_1/model_epoch700.onnx"
