scaleout: 400
chunksize: 50000
mem-per-worker: "2GB"
disk-per-worker: "4GB"
queue: "short"
walltime: "1:00:00"
adaptive: true
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
spanet_model: "/pnfs/psi.ch/cms/trivcat/store/user/mmarcheg/ttHbb/models/meanloss_multiclassifier_btag_LMH/spanet_output/version_0/spanet.onnx"
